name: crudapp
recipe: laravel
config:
  php: "8.0"
  composer_version: '2.2.7'
  # via: apache:2.4
  webroot: ./public
  database: mysql:8.0
  cache: redis
  # xdebug: false

services:
  appserver:
    scanner: false
    run_as_root:
      - composer self-update
    run:
      - composer install

  node:
    type: node:16
    ssl: false
    command: tail -f /dev/null
    globals: [ ]
    port: 80

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
tooling:
  node:
    service: node
  npm:
    service: node
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /vendor/bin/phpunit

excludes:
  - vendor
  - node_modules

